[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
vault = "FnjZB6c8Z42YprQmZKQ2z72naCoXYPUqUue6D8TgWmRK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
